### PR TITLE
GUI test mode and New versioning system ported to Makefile.win, new versioning layout. [STATUS: STABLE]

### PR DESCRIPTION
**Pull request by Ownasaurus**
For times like these where you want to test the GUI but don't have your own meter, you can now change #define USE_SERIAL 1 to #define USE_SERIAL 0 to simulate received data. Thought you might want this feature in your master.

Unfortunately I cannot test your new versioning system even with this change because I have to use two different environments for my git and for my mingw... so I just get V0 when I compile it :(.

### CODE REVIEW

**Comment by Ownasaurus** [comment]
If you have don't have windows/wine and you send me a compiled binary using USE_SERIAL 0, I'd be happy to check the versioning system you added.

**Comment by Ownasaurus** [comment]
@Nullkraft Can you please test with an actual meter? I changed some of the refresh code since I was getting some flickering text.

@inflex 

- I tried improving the location of the version. Want to take a look at it? You should be able to now. If not, I'll send a screenshot.
- I changed the order of some of the GUI creation commands becaues GetDC() was being called on an uninitialized HWND, i think.
- Looks like -c was half implemented already and not in the help file. So i replaced my "USE_SERAL 0" with the -c command line parameter and finished implementing it
- I messed with some of the spacing in the print statements. Were those %-04s needed? I tried to simplify it.

**Comment by Nullkraft** [comment]
OK, here's the location with 2 new files that have "build_num" in filename.

https://drive.google.com/open?id=1S_7spABVIJSQ1zgiJgRwDWcgYcmnr1rp

**Comment by Ownasaurus** [comment]
OK great, thanks. Is the mouse issue still not there? and no flickering?

**Comment by Nullkraft** [comment]
I never had a problem with flickering but I just went to make sure and now it only updates the display one time on startup.  I'm not getting any numerical updates at all.  I checked to see if inflex copy works and it does so it's not a problem with my system.

**Comment by Ownasaurus** [comment]
Yes that's exactly what I wanted to test. Thank you.  Try again now, please.
1. Does it refresh?
2. Does it flicker?

Cause I can only test a static screen in the noserial mode

**Comment by Nullkraft** [comment]
That fixed refresh.  And I don't see any kind of flickering at all.  Want to come over and look?

**Comment by Ownasaurus** [comment]
No thanks. The flickering I see on my end is too rapid to see over remote desktop. I'm glad it doesnt happen for you, though!

**Comment by Nullkraft** [comment]
Are you testing by using the no_serial, or whatever you call that testing flag?

**Comment by Ownasaurus** [comment]
Yes.  I just add -c in the command line parameters. It simulates reading 432.1 ohms of resistance. Feel free to try it. Do you get flickering with -c?

**Comment by Nullkraft** [comment]
Yes, the [B60] is flickering now

**Comment by Ownasaurus** [comment]
Ah ha! It was flickering because without actual serial reading, it was looping so quickly. I added a 100ms delay in -c mode, and now it looks fixed. 

Thank you so much for testing! Feel free to test this latest version, but I bet it will work in all modes :)

**Comment by Nullkraft** [comment]
No more flickering for [B61]

**Comment by Nullkraft** [comment]
100ms.  That's why I asked.  Had the same problem in the Arduino when updating the LCD screen.

**Comment by Ownasaurus** [comment]
Thanks for your testing, @Nullkraft. I wonder what Paul will think of the new location of the version. Do you like it better in the upper left corner?

**Comment by Nullkraft** [comment]
It looks a lot less distracting up in the top left corner.  Much better.  I just uploaded a screen shot to the google share but if you look at it there is a tiny little corner that's cutting into the first 0 on the left.

**Comment by Ownasaurus** [comment]
Oh, I see. That's both subtle and unfortunate. I'll leave it to @inflex to decide what to do with it. But at least most of the changes are useful.

**Comment by Nullkraft** [comment]
Sounds good to me.  And by the way, the startup is exactly as fast for both inflex and your versions.  Checked it and thought you should know.

Was there anything else you needed to see?

**Comment by Ownasaurus** [comment]
All good, thanks. I'm calling it stable now even though there can be that like 1 pixel of overlap sometimes.

**Comment by Nullkraft** [comment]
Cool.  I expect inflex may contact me so I'll just mention here that I'm going to tell him that when exiting the app it takes as long as the next serial update before it will close.  Makes it feel really sluggish.

**Comment by Ownasaurus** [comment]
That should be in the old version too right? Cause it's waiting at a blocking sleep for the serial port to receive data.

**Comment by ghost** [comment]
Can you make a consolidated PR on this one, because reading through the first few commits I'm considering just binning this one, a lot of changes for a small, almost never going to be used feature that probably might be better off just being something we comment out  or set via an ENV VAR rather than doing all the coding changes.

**Comment by ghost** [comment]
ie, realistically, we could have something more like;

#ifdef FAKE_COMMS
 d[] = { 0x34, 0x30, 0x82 ....... }
#else 
 (do normal serial block read)
#endif

**Comment by ghost** [comment]
Sorry I've done things very differently to what you were going for - here's the commit I've done

https://github.com/inflex/BK-390A/commit/d3eb510cdbd0412e996b3ce67df896016c6a2915

**Comment by Ownasaurus** [comment]
Don't be sorry -- it's your project. But I do think it's a straight disadvantage in my opinion to have to recompile to test a feature instead of just pass a command line parameter.

Also it didn't include changes to my Makefile.win, which mirrors the changes to your Makefile. So I will submit another PR for that.

**Comment by Ownasaurus** [comment]
Also what is your -c supposed to do? It's not in the help file but it is looked for in the parameter parsing? I would recommend either removing it or fully supporting it

**Comment by ghost** [comment]
-c was likely a development flag that I simply didn't cull out at the end of the process.

Tends to often be many of these hidden flags / options that don't get removed after the system gets up and running, or they're simply forgotten over time, but it's also more trouble than it's worth to yank out all the logic infrastructure, particularly when you've got something just working.   Sort of stuff that'll be purged when the time for refactoring comes around.

**Pull request closed without merging**
