### PR TITLE
added windows Makefile and auto port detection code

### PR DESCRIPTION
**Pull request by Ownasaurus**
Although I haven't yet gotten the recommend development environment to work, I think some of these changes are in the right direction. For the non-gui version, sometimes .exe is present, and sometimes it is not. I tried to make it standardized (always .exe present).

### CODE REVIEW

**Comment by Ownasaurus** [comment]
Commit b0d1e5b is probably good for master. However, commit 5c28244 might make more sense to go into a windows branch.

**Comment by Ownasaurus** [comment]
Thanks. I'm too newbie to know make took a -f parameter hehe :) I'll do that in the next few minutes. I was going to try and make a branch but you're right it's probably better to just make a new makefile

**Comment by ghost** [comment]
All good.  It's not the perfect "one click" type solution but it's a very simple/effective alternative solution which often is a lot easier than trying to bring in things like autoconfig tools or cmake (for small projects like this).

**Comment by Ownasaurus** [comment]
OK. I think it's in a better place now. Please review the changes at your convenience. I can confirm it works on my Windows 10 machine with MinGW-w64 using "mingw32-make -f Makefile.win bk390a" and "mingw32-make -f Makefile.win win-bk390a". "mingw32-make -f Makefile.win clean" also functions properly.

**Comment by Ownasaurus** [comment]
First revision of win32 autodetect code is complete. The only thing I am unsure about is the length check I do. Please see line 491. Do we always receive 11 packets per transmission?

**Comment by ghost** [comment]
Just letting you know, I'm not ignoring your commits/PRs, just thought I'd give it a few days until everything is settled down so I can review the whole lot as a single consolidated commit.

**Comment by Ownasaurus** [comment]
Thank you for your feedback. Although the future is always uncertain, I think I just made the last few changes I can without having access to the device; I do not expect to commit any more this week unless we are able to get some debug information.

The main thing I am unsure about is the "11 packets per transmission" assumption. If you can confirm that part of the code, we should be golden :). Do you think you can get Louis to run this with -d to ensure it is functioning correctly?

**Comment by ghost** [comment]
The 11 bytes per "Frame" is what is specified in the spec.  Though I run on the idea that there may be broken frames that are either greater or less than 11 bytes.  The main thing to look for is if we get the delimeters (\r\n) and when we have them, is the size of the frame correct; if not, then discard and wait again.

You'll likely have noticed by now that this serial code is **blocking** in nature, which isn't the most ideal thing but for the purpose / task it's being used in it's not such a big risk.   Converting it to a non-blocking version is more work and more bugs.  I'd consider it for much later revisions.

**Comment by Ownasaurus** [comment]
In this case, I hope checking if(i % 11 == 0) is correct logic after receiving the \n.
I also do a second formatting check for kicks which can't hurt.

Due to the blocking nature of the code, when I'm trying to detect the correct port, I remove a WaitSerialComm call (which would block indefinitely on a bad port) and instead replace it with a Sleep(2000). Then, it can progress to ReadFile which does timeout successfully. The assumption is that the device communicates at least once within 2 seconds.

If you have any questions about the code changes, please let me know.

**Comment by ghost** [comment]
Getting there... getting there.

Really need a live BK390 to test with.

**Comment by Ownasaurus** [comment]
I can only think of 4 options from here:
1) Louis or one of his employees acquires the debug capture.
2) For Louis I think time is money... maybe he'll sponsor one for me to borrow? I only say me and not you because I live 45 minutes from his store and can easily ship it to him or drive it to him when we're done debugging the issue(s).
3) We find someone else who has the meter and is willing to get a debug capture
4) One of us gives in and buys one because fixing things and checking things off the list feels good

Since you have a good relationship with him, I'm hoping you can get #1 or #2 to happen :)

**Comment by ghost** [comment]
#1 is the most realistic option, but it's a game of patience.

I won't be buying one of these meters, costs too much here in AU, particularly on the back of its limitations.  I'll be in the market though for a benchtop one soon.

**Comment by Ownasaurus** [comment]
Since a lot of viewers apparently buy Louis' hardware, I'm wondering if #3 has a decent chance at happening.

**Comment by Ownasaurus** [comment]
Base has been changed too much. Will adjust code and submit new request

**Comment by ghost** [comment]
Sorry about that - didn't think it was -that- severe :(

**Comment by Ownasaurus** [comment]
It really isn't, but this way it will be easier for you to merge. Just want to make your life easier.

**Pull request closed without merging**
