### PR TITLE
Cleaned up some logic. [STATUS: STABLE]

### PR DESCRIPTION
**Pull request by Ownasaurus**
In case you want to take my cleaned up version rather than do it yourself

### CODE REVIEW

**Comment by Ownasaurus** [comment]
- Tried to clean up the code. Of course, you can be the final judge of that :)
- Auto port detection seems to work just fine
- Fixed a bug where the window would not update if the mouse was over it

The above was confirmed with the help of @Nullkraft

**Comment by Ownasaurus** [comment]
Another interesting side-effect of my code changes is that I don't get a weird extra 3rd packet per cycle being the single byte "\n" anymore.

**Comment by ghost** [comment]
I think you'll find that 3rd frame was an artifact of the 1-off issue originally.  

Easy way to test, get @nullkraft to try the master with the debug mode again.

**Comment by Ownasaurus** [comment]
Either way i'm pretty certain it's ready to merge when you're ready to review.
@Nullkraft could you test the latest version of @inflex 's build before this gets merged in debug mode and see if you get the erroneous 3rd frames?

**Comment by Nullkraft** [comment]
I'm at work right now so it'll be about 8 hrs from now before I can test it.

**Comment by Ownasaurus** [comment]
@Nullkraft 's results are in the closed units prefix thread. We still get odd frames sometimes but less consistently. I think the same is true for my code.

Louis said he hasn't updated yet. I'd recommend merging in my fixes before he updates so he gets all the features at once if he does update since it's an uncommon event!

**Comment by ghost** [comment]
Can I get 100% confirmation that the software works with the old parameter style too; because Louis will be using an overwrite of the software, so the old parameters will still exist (no autodetection).

**Comment by Ownasaurus** [comment]
@nullkraft did many tests with -p and it still works

**Comment by Ownasaurus** [comment]
do you have a sample parameter string to test? he tested -p, -d, and -m explicitly.

**Comment by ghost** [comment]
Use the one that's detailed in the help section (with appropriate com port of course :) )

**Comment by Ownasaurus** [comment]
just noticed "bk390a.exe -z 120 -p 4 -m -fc #ff1010 -bc #000000 -fw 600" should probably be "win-bk390a.exe -z 120 -p 4 -m -fc #ff1010 -bc #000000 -fw 600".  i'll add that change too in my fork.

@Nullkraft, can you try running the program with -z 120 -p 3 -m -fc #ff1010 -bc #000000 -fw 600 or something similar as a final confirmation? Thanks so much for your support!

**Comment by Ownasaurus** [comment]
@Nullkraft said:

> I tried the command line: win-bk390a.exe -z 120 -p 3 -m -fc #ff1010 -bc #000000 -fw 600
and everything seems to be working fine. I changed -z a few times and had good control. I got a rather large red font in the display.

> I will mention one thing, when I set -z to a relatively small value (less than 25) the display began to cutoff portions of the information, namely the description(?) such as the word 'Frequency'.

Just moving it to our correct discussion thread. Thanks for the info! Looks ready to rock and roll :)

**Comment by ghost** [comment]
You're right about the font width issue; that's because there's no function that I can see in the GDI system that lets you know the width of the text box that you've created (maybe there is, I haven't found it yet), either that or I was too lazy to work it out and just thumb-sucked it.... both scenarios are equally likely ;)

**Comment by Ownasaurus** [comment]
Anything else you want tidied up before merge? I have about 40 minutes of free time atm

**Comment by Ownasaurus** [comment]
Fantastic. Do you want to increment the version again?  Just curious.
I'm going to follow this project and will help if more development is required. Fun working with you :)

**Comment by inflex** [comment]
I'm fixing up the version thing right now - don't make any changes yet, I'm tying it to git releases

**Comment by inflex** [comment]
New versioning information system is added. Pulls from the git release data.

**Pull request merged**
